Обработка датасета

In [1]:
import pandas as pd
import csv
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/comments.csv")

In [3]:
df

,sentiments,cleaned_review,cleaned_review_length,review_score
0,positive,i wish would have gotten one earlier love it a...,19,5.0
1,neutral,i ve learned this lesson again open the packag...,88,1.0
2,neutral,it is so slow and lags find better option,9,2.0
3,neutral,roller ball stopped working within months of m...,12,1.0
4,neutral,i like the color and size but it few days out ...,21,1.0
...,...,...,...,...
17335,positive,i love this speaker and love can take it anywh...,30,5.0
17336,positive,i use it in my house easy to connect and loud ...,13,4.0
17337,positive,the bass is good and the battery is amazing mu...,41,5.0
17338,positive,love it,2,5.0
17339,neutral,mono speaker,2,5.0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17340 entries, 0 to 17339
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sentiments             17340 non-null  object
 1   cleaned_review         17337 non-null  object
 2   cleaned_review_length  17340 non-null  int64
 3   review_score           17340 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 542.0+ KB

In [38]:
df.columns

Index(['sentiments', 'cleaned_review', 'cleaned_review_length',
       'review_score'],
      dtype='object')

In [39]:
df['sentiments'].value_counts()

sentiments
positive    9503
neutral     6303
negative    1534
Name: count, dtype: int64

In [40]:
df.isna().sum()

sentiments               0
cleaned_review           3
cleaned_review_length    0
review_score             0
dtype: int64

In [7]:
df_clean= df.dropna(subset = ["cleaned_review"])

In [8]:
df_clean

,sentiments,cleaned_review,cleaned_review_length,review_score
0,positive,i wish would have gotten one earlier love it a...,19,5.0
1,neutral,i ve learned this lesson again open the packag...,88,1.0
2,neutral,it is so slow and lags find better option,9,2.0
3,neutral,roller ball stopped working within months of m...,12,1.0
4,neutral,i like the color and size but it few days out ...,21,1.0
...,...,...,...,...
17335,positive,i love this speaker and love can take it anywh...,30,5.0
17336,positive,i use it in my house easy to connect and loud ...,13,4.0
17337,positive,the bass is good and the battery is amazing mu...,41,5.0
17338,positive,love it,2,5.0
17339,neutral,mono speaker,2,5.0

In [42]:
df_clean.isna().sum()

sentiments               0
cleaned_review           0
cleaned_review_length    0
review_score             0
dtype: int64

In [10]:
df_size = df_clean.loc[:, ['cleaned_review', 'sentiments']]

In [11]:
df_size

                                          cleaned_review sentiments
0      i wish would have gotten one earlier love it a...   positive
1      i ve learned this lesson again open the packag...    neutral
2              it is so slow and lags find better option    neutral
3      roller ball stopped working within months of m...    neutral
4      i like the color and size but it few days out ...    neutral
...                                                  ...        ...
17335  i love this speaker and love can take it anywh...   positive
17336  i use it in my house easy to connect and loud ...   positive
17337  the bass is good and the battery is amazing mu...   positive
17338                                            love it   positive
17339                                       mono speaker    neutral

[17337 rows x 2 columns]

In [56]:
df_size["sentiments"].value_counts()

sentiments
positive    9503
neutral     6300
negative    1534
Name: count, dtype: int64

In [12]:
df_size["sentiments"] = df_size["sentiments"].replace("negative", 2)
df_size["sentiments"] = df_size["sentiments"].replace("positive", 1)
df_size["sentiments"] = df_size["sentiments"].replace("neutral", 0)

C:\Users\s7omb\AppData\Local\Temp\ipykernel_16624\122639735.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_size["sentiments"] = df_size["sentiments"].replace("neutral", 0)

In [14]:
df_size

                                          cleaned_review  sentiments
0      i wish would have gotten one earlier love it a...           1
1      i ve learned this lesson again open the packag...           0
2              it is so slow and lags find better option           0
3      roller ball stopped working within months of m...           0
4      i like the color and size but it few days out ...           0
...                                                  ...         ...
17335  i love this speaker and love can take it anywh...           1
17336  i use it in my house easy to connect and loud ...           1
17337  the bass is good and the battery is amazing mu...           1
17338                                            love it           1
17339                                       mono speaker           0

[17337 rows x 2 columns]

In [58]:

df_size["sentiments"]

0        1
1        0
2        0
3        0
4        0
        ..
17335    1
17336    1
17337    1
17338    1
17339    0
Name: sentiments, Length: 17337, dtype: int64

In [59]:
df_size["sentiments"].value_counts()

sentiments
1    9503
0    6300
2    1534
Name: count, dtype: int64

In [60]:
df_size.to_csv("../src/data/data.csv")